In [7]:
import json
import torch

from model import load_model, my_hash, parse_json


In [8]:
user_ids = ["f34d7147-9d39-4145-bc7e-3a3c05029035", "46b5b420-3317-4a14-9c90-9dc4206cf960"]
media_ids = ["01HEKK737WXFC9TWQ036XDS0QH", "01H2K82V8XCKGD882FPQ3TQ9WF"]


In [9]:
model = load_model("model_dir/model.pth")
model

CollaborativeFilteringModel(
  (user_embedding): Embedding(50000, 4)
  (post_embedding): Embedding(1800, 4)
)

In [10]:
ut = torch.tensor(list(map(lambda x: my_hash(x), user_ids)))
mt = torch.tensor(list(map(lambda x: my_hash(x), media_ids)))
ut, mt

(tensor([2801485989, 3674906565]), tensor([437423269, 306905446]))

In [11]:
model(ut, mt)

tensor([0.2007, 0.5149], grad_fn=<SigmoidBackward0>)

In [14]:
js = """
{
    "user_ids": ["f34d7147-9d39-4145-bc7e-3a3c05029035", "46b5b420-3317-4a14-9c90-9dc4206cf960"],
    "media_ids": ["01HEKK737WXFC9TWQ036XDS0QH", "01H2K82V8XCKGD882FPQ3TQ9WF"]
}
"""
# js = json.loads(js)
js

'\n{\n    "user_ids": ["f34d7147-9d39-4145-bc7e-3a3c05029035", "46b5b420-3317-4a14-9c90-9dc4206cf960"],\n    "media_ids": ["01HEKK737WXFC9TWQ036XDS0QH", "01H2K82V8XCKGD882FPQ3TQ9WF"]\n}\n'

In [15]:
ut, mt = parse_json(js)
model(ut, mt)

tensor([0.2007, 0.5149], grad_fn=<SigmoidBackward0>)